version: '3.8'

services:
  simulator:
    container_name: simulator
    image: ghcr.io/laendleenergy/simulator:latest
    volumes:
      - ./mqtt_messages_2.json:/mqtt_messages_2.json
    environment:
      - BROKER_ADDRESS=45.145.224.10
      - BROKER_PORT=1884
      - ROOT_TOPIC=simulator
      - DATA_FILE_NAME=./mqtt_messages_2.json
      - USE_CERTIFICATES=false